blank_issues_enabled: false
contact_links:
  - name: ğŸŒ FocusCursor Official Website
    url: https://wangchujiang.com/focus-cursor/
    about: Introduction to the FocusCursor app on the official website!